### ISSUE TITLE
isInteger IE <= 11

### ISSUE THREAD

**Issue by miguelcast** [LoicMahieu/react-styled-flexboxgrid#50]
Display error on Internet Explorer <= 11:

TypeError: El objeto no acepta la propiedad o el método 'isInteger'
TypeError: Object doesn't support this property or method
   at Anonymous function (http://localhost:3000/_next/-/commons.js:49793:1)
   at Anonymous function (http://localhost:3000/_next/-/commons.js:49789:17)
   at Anonymous function (http://localhost:3000/_next/-/commons.js:41106:3)
   at flatten (http://localhost:3000/_next/-/commons.js:41098:58)
   at generateAndInjectStyles (http://localhost:3000/_next/-/commons.js:48676:5)
   at generateAndInjectStyles (http://localhost:3000/_next/-/commons.js:48417:7)
   at Anonymous function (http://localhost:3000/_next/-/commons.js:48438:11)
   at subscribe (http://localhost:3000/_next/-/commons.js:48266:3)
   at componentWillMount (http://localhost:3000/_next/-/commons.js:48429:9)
   at Anonymous function (http://localhost:3000/_next/-/commons.js:26950:11)

**Comment by miguelcast** [comment]
Thanks for solving this so fast.
